### ISSUE TITLE
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))

### ISSUE THREAD

**Issue by stephanbracke** [geomagpy/magpy#105]
On environment : 

- windows 10  
- python 3.9 
- wxPython 4.1.1

The C++ wxAssertionError pops up when opening a file which leaves the magpy display on the intro screen and doesn't display any  graph.
The same happens when using the python 3.7.4 environment with wxPython 4.1.0.
Using wxPython 4.1.1 on python 3.7.4 causes a locale error which is solved when using higher version of python

**Comment by leonro** [comment]
Done and tested for version 1.0.3: (2b845aefa69fb16191b2fd224f372652faf81167). A new windows installer based on python 3.9 and newest wxpython is in preparation.
