### ISSUE TITLE
In export function 'youforgottodefineafilename' appended to the file is not desirable

### ISSUE THREAD

**Issue by stephanbracke** [geomagpy/magpy#116]
We noticed on some exports ( espacially imfv and cdf) If the name of the file is not filled in, we have an append of 
'youforgottodefineafilename' before altough the timepattern is sufficient and correct. This makes it necessary to manually correct the name afterwards. It is due to two lines in the code 

https://github.com/geomagpy/magpy/blob/ae91462f1644ebf89fbe570ce1cf67d1d89eb926/magpy/gui/magpy_gui.py#L2732-L2733

For the moment I commented them out which solved the problem for us when doing the imfv/cdf  exports

**Comment by leonro** [comment]
Corrected in bcc1cb884c2ae8532b13fd14ddfcaa07878115ed
