### ISSUE TITLE
xmagpy: No blvoutput field in "Analysis parameter" dialogue

### ISSUE THREAD

**Issue by mlnorthernswe** [geomagpy/magpy#128]
We have an xyz oriented parameter. In the xmagpy documentation in section 4.5 about the "DI panel" it is written: "If you want to export baseline values in geographic XYZ coordinates please insert “XYZ” into the blvoutput field within the analysis parameter dialog.". However I can't found blvoutput field in the analysis parameter dialogue. 
In log-file after analysing in DI panel it is written:
variometer data contains the following components: XYZF
Variometer data provided in XYZ, Basevalue outpus projected in HDZ, however, 
as variometerorientation is not manually confirmed to be xyz (see manual)

**Comment by leonro** [comment]
This is an issue with the .magpyguiini file. This is already on my TODO list, but not yet solved. The .magpyguiini should be extended with "new" options of future versions of xmagpy. This is however not yet working properly. 
At the moment I have only the following quick solution:
- if you have changed the default options: please make a copy/screenshot of xmagpy options in   (basic initialization/DI initialization)
- delete the file .magpyguiini in your home directory
- restart xmagpy
- the new "blvoutput" is now available
- please check all other options and eventually change them to the previously used ones

**Comment by mlnorthernswe** [comment]
Yes, now I can see the blvoutput option. Thank you!
