### ISSUE TITLE
Baseline Correction button in xmagpy not enabled

### ISSUE THREAD

**Issue by mlnorthernswe** [geomagpy/magpy#129]
Probably I'm doing something wrong here, but I follow the [wiki ](https://github.com/geomagpy/magpy/wiki/GUI:-Producing-a-baseline ) on how to produce a baseline with xmagpy (version 1.1.7).  
Absolute measurement data can be found here: [absolute measurements](https://www2.irf.se/maggraphs/absolute_measurements/)  
Variometer and scalar data can be found here: [variometer and scalar data](https://www2.irf.se/maggraphs/maglinux/vario_scalar/)  
Logs: [magpy logs](https://www2.irf.se/maggraphs/magpy/logs/)  
  
We are using a XYZ-oriented magnetometer.  
  
I do the following steps:  
1. Load DI-data. In this case for month 2023-10 which are the absolute measurements [2023-09-11](https://www2.irf.se/maggraphs/absolute_measurements/2023-09-11_07-56-10_MIR2_KIR.txt), [2023-10-10](https://www2.irf.se/maggraphs/absolute_measurements/2023-10-10_09-29-15_MIR2_KIR.txt), [2023-10-16](https://www2.irf.se/maggraphs/absolute_measurements/2023-10-16_10-04-58_MIR2_KIR.txt), [2023-10-23](https://www2.irf.se/maggraphs/absolute_measurements/2023-10-23_12-12-15_MIR2_KIR.txt) and [2023-11-02](https://www2.irf.se/maggraphs/absolute_measurements/2023-11-02_08-57-28_MIR2_KIR.txt).
2. As we have a XYZ-oriented magnetometer I choose Data->Select components->xyz.
3. Then I export the absolute measurements data to PYSTR ([exported data](https://www2.irf.se/maggraphs/magpy/exported_data/)).
4. I load the exported data. File->Open File (choose the exported BLV_*-files).
5. Go to panel Analysis and choose Fit (applying spline, knots 0.3 on the data in question).
6. Load variometer files for the month in question (in this case 2023-10) in [variometer and scalar data](https://www2.irf.se/maggraphs/maglinux/vario_scalar/).
7. To adopt baseline I go to Analysis panel and press button Baseline and choose the appropriate Baseline for the adoption.
8. The message "Adopted baseline calculated. Baseline parameters added to meta information and option 'Baseline Corr' on 'Data' panel now enabled." appears. I press OK.
9. Goes to the panel Data but the 'Baseline Corr' option is not enabled!

Is it something wrong in the above procedure or in the data?

/Regards Mats

**Comment by mlnorthernswe** [comment]
When I tried with a different dataset. The month of 2023-08 it seems to work. So there is some kind of problmen with the dataset of the month 2023-10 that xmagpy reacts to.

**Comment by mlnorthernswe** [comment]
I see now in the logs the warning "Warning! Variation data missing at DI time range" so it seems to be some gaps in our data that leads to the problems decribed above with 'Baseline Corr'-button not enabled. I must check that.

**Comment by mlnorthernswe** [comment]
I found a bug in my software that marked data as gaps even if there were no gaps. So there is the reason probably that the 'Baseline Corr'-button was not enabled.

**Comment by leonro** [comment]
So I guess I can close this one.
