### ISSUE TITLE
Large combo box issue

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#28]
wxWidgets on Mac complains about:

> This application is trying to draw a very large combo box, 30 points tall.  Vertically resizable combo boxes are not supported, but it happens that 10.4 and previous drew something that looked kind of sort of okay.  The art in 10.5 does not break up in a way that supports that drawing.  To avoid breaking existing apps, NSComboBox in 10.5 will use the 10.4 art for large combo boxes, but it won't exactly match the rest of the system.  This application should be revised to stop using large combo boxes.  This warning will appear once per app launch.

I guess this comes from
~~~~~python
self.formatComboBox = wx.ComboBox(self, choices=self.WriteFormats,
    style=wx.CB_DROPDOWN, value=self.WriteFormats[self.default], size=(160,30))
~~~~~
at several places.

**Comment by leonro** [comment]
Finished with 6a3d4ab11080af05f7b77b923108c07d41945300. Setting size to (160,-1). Please reopen if not working on Mac.
Closing #28
