### ISSUE TITLE
Pressing Cancel in almost any dialog freezes the GUI / leaves it in a weird state

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#29]
After trying to export and cancelling name modification, the GUI becomes unresponsive (as if the window for name modification was still active). The only way to exit the program is then to use Ctrl-C.

Similar problem is observed when clicking on Flag Outlier, Select columns, ... followed by Cancel.

**Comment by mojca** [comment]
[This](https://trac.macports.org/browser/trunk/dports/python/py-magpy/files/patch-magpy-gui-dialogclaes.py.diff?rev=152537) changes seems to have helped, but it has to be tested on Linux and Windows.

**Comment by leonro** [comment]
Tested on Linux. Working perfectly. Windows test still to be done.

**Comment by leonro** [comment]
Issue solved with f4813b2e86233f591742c4a21a27fd36fde52216
Windows test remains open so I keep it open.

**Comment by leonro** [comment]
Finished with 6a3d4ab11080af05f7b77b923108c07d41945300.
Closing #29
