### ISSUE TITLE
Select components doesn't properly switch the components

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#30]
After opening `xyz` data and clicking on `hdz` to switch the components, the radio button jumps back to `xyz`. Then one can click on `hdz` again and do another `xyz->hdz` transformation.  The radio button should probably move to `hdz` and not allow applying the same calculation again.

Also, changing parameters like `colorlist` in Plot options seems to be reset.

**Comment by leonro** [comment]
Issue solved in 52d9dce184c0c014ab9cb451dd6ba079ee98f745
