### ISSUE TITLE
DI analysis parameters should support browsing for the path

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#37]
It would be nice if I could browse for the path (DI path, DI variometer, DI scalar) rather than having to copy-paste it manually.

**Comment by leonro** [comment]
copy and paste is not necessary. selecting the appropriate path either in the DI panel or from the DI menu updates these inputs. marked and noted that accordingly.

**Comment by leonro** [comment]
Finished with 6a3d4ab11080af05f7b77b923108c07d41945300.
Closing #37
