### ISSUE TITLE
Pressing cmd+C on Mac in absolute entry sheet closes the window

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#39]
cmd+C is used to copy the contents. If pressed in an absolute entry sheet, it closes the window instead of copying the data.

On top of that I believe the window should ask for saving the data before closing itself to prevent unintentional loss of data.

**Comment by leonro** [comment]
This issue is solved with 74f9edcae4f996c79494c21f9c1006fc48b912e3 .
I also added a confirmation window.
Tested on MacOS 10.12.3.
