### ISSUE TITLE
acquisition.arduinoprotocol os.walk() only works on Linux

### ISSUE THREAD

**Issue by bairaelyn** [geomagpy/magpy#4]
Search for correct path in arduinoprotocol is not Windows or Mac friendly:

`martasdir = [path for path, dirs, files in os.walk("/home") if path.endswith('MARTAS')][0]`

May also be present in other protocols. Better if this is replaced with a reference to the current path if acquisition is always called from the MARTAS directory.

**Comment by leonro** [comment]
There is another issue with the same line: if a MARTAS directory is already existing in another subfolder of the home directory (e.g. Trash) then eventually this folder is selected as main MARTAS directory and any requests for sensor info or the automatic generation of arduino and one wire ID lists will fail.

**Comment by leonro** [comment]
Solved in 13ae729583eaa2dce6e8b6019a7a960e7b20dae9.
Will keep it open until tested on raspberry.

**Comment by leonro** [comment]
Tested. Closing this one.
