### ISSUE TITLE
DI-sheet parametrisation: residual correction factor

### ISSUE THREAD

**Issue by teraita** [geomagpy/magpy#61]
Fix needed for DI sheet / parametrisation: Residual correction factor for DI calculation: 1 or -1 

The sign depends on which way the sensor coil is connected to electronics and varies from sensor to sensor and manufacturer. Easy to test correct sign:
If turning from WestUp  to northward is positive , then the factor is  -1.
If negative, then factor is +1.
More information: Jankowski & Sucksdoff, 1996 p. 89 and 94.

**Comment by leonro** [comment]
Hi Tero, I have included your fix into the new version (see commit 425f87425d06558d28c2326406df015cb8bd5cd7). It will be uploaded together with a couple of other updates in version 0.3.8, as soon as I finished the runtime tests (most likely tomorrow). You can then select between inline and opposite fluxgate orientation, which will flip the sign of provided residual values for calculation when saving data. Please check, whether this approach is suitable...  
Cheers, Roman
PS: I will keep this issue open until feedback.

**Comment by leonro** [comment]
Will close this issue now. Seems to solved.
