### ISSUE TITLE
DI-sheet: various issues

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#63]
I can open several separate issues if needed, but since most of them are related, I list them at the same place.

* I miss an optional field for observer notes.
* When there is a problem in the input sheet, the feedback is slightly annoying. It doesn't tell where exactly the problem is (not even the info about what the problem was is clear) and it raises the error message many times (one popup for each error). It would be useful to get just a single error message and perhaps some markers (red border around input fields?) telling where exactly the problems are.
* Observers usually manually calculate the horizontal angle for inclination measurements. While this is a bit redundant (magpy can calculate it itself of course), it would be a very useful check. It might be that the observer miscalculated the angle and the I measurements were done at a different horizontal orientation. This problem should be caught (and can also be corrected with HP's method).
* The program doesn't ask for confirmation when overwriting an existing file and doesn't really provide feedback if one doesn't store the latest changes.
* The hour should be stored as "08" rather than "8" for a single digit. It's suboptimal for file sorting to use single digits. This holds both for the file format (numbers written in the file) as well as for filenames themselves.

Feature requests:
* It would be useful to have support for more than a single target. We often measure two targets at the same time. Even if the second target would not be included in the final calculation, it would be useful to have it there for a double-check without having to retype the complete measurement in a new form.
* It would be great to support more than one (or two) measurements on request (I can imagine some kind of a `+` sign in the form to add an additional measurement in case there was something suspicious about the previous one).
* It would be really nice if magpy would do some conversions back to `DD:MM:SS.S` when reviewing or fixing old data.
* Provide a local "database" of available theodolites, variometers, observers etc. for autocompletion. It's slightly suboptimal having to retype the same instrument information each time.

**Comment by leonro** [comment]
The following points have been included/corrected in 90e32dcc5285b9035814e83a68c6fecd05f7c224:
- added observer notes field
- horizontal angle calculation (added button, to do and show that).
- added overwrite confirmation if file existing
- hours are stored correctly even if input is 8:34:23

Missing: input sheet feedback

Regarding feature requests:
- conversion between deg.decimal and deg:min:sec can be done using radio button upper right
- local database, retyping issue: we usually do that be creating templates: store a typical data sheet, copy that to a new file e.g. template.txt.

Missing: multiple inputs

**Comment by leonro** [comment]
With commit 74f9edcae4f996c79494c21f9c1006fc48b912e3 I added coloured feedback information to the DIInputSheet and limited the amount of error messages to one for each information type.

Still Missing: multiple inputs

**Comment by leonro** [comment]
Repeated measurements are now simplified with ce09da3bf6e43efd340cad830046493e0a49622e.
Still only one azimuth/measurements for one orientation is allowed. You can however simply change the azimuth measurement after storing and press save again. You will now find the option "save alternative" which slightly changes the file name (adding one second) but not the content. Thus you can analyse both data sets. In a similar way, repeated measurements can be treated.
From my point of view all issues have been approached. Will keep it open until merged with master.

**Comment by leonro** [comment]
Will close this issue now as all issues have been dealed with (1619752ff2d9b37f67a348f1b95eccc74a51848c). Version 0.3.95 includes all changes.
