### ISSUE TITLE
Warning about large combo boxes

### ISSUE THREAD

**Issue by mojca** [geomagpy/magpy#64]
When opening the DI input sheet this is the warning thrown by xmagpy on OS X:

> Python[3273:60b] This application is trying to draw a very large combo box, 30 points tall.  Vertically resizable combo boxes are not supported, but it happens that 10.4 and previous drew something that looked kind of sort of okay.  The art in 10.5 does not break up in a way that supports that drawing.  To avoid breaking existing apps, NSComboBox in 10.5 will use the 10.4 art for large combo boxes, but it won't exactly match the rest of the system.  This application should be revised to stop using large combo boxes.  This warning will appear once per app launch.

**Comment by mojca** [comment]
It's not exactly clear to me what is going on here. It seems that any combobox would trigger this warning and render suboptimally. I could check if switching to another wxWidges version would help (wxPython 3.0.2 is super old, but I doubt that wxPython 4 works anyway).

**Comment by leonro** [comment]
Please check the new version: 90e32dcc5285b9035814e83a68c6fecd05f7c224. All ComboBoxes of the DI Input sheet should be configured correctly. Working fine on Windows and Linux. Still cannot check myself on Mac.

**Comment by leonro** [comment]
This issue is solved with 74f9edcae4f996c79494c21f9c1006fc48b912e3 .
Quiet interesting: needed to relax the size of all other TextFields within the ComboBox Line (within a FlexGrid). Well its working now and no warning are issued any more.
Tested on MacOS 10.12.3.
