### ISSUE TITLE
Conflicting menu hotkeys for Cmd/Ctrl+I and Cmd/Ctrl+L

### ISSUE THREAD

**Issue by jmfee-usgs** [geomagpy/magpy#87]
There are conflicting hotkeys for menu options.
Cmd+I:
![](https://user-images.githubusercontent.com/26904055/33138304-61be0a10-cf67-11e7-8587-31b3c8a39dce.png)
![](https://user-images.githubusercontent.com/26904055/33138307-62e99b7a-cf67-11e7-86ba-8ee0b72300dc.png)

Cmd+L:
![](https://user-images.githubusercontent.com/26904055/33138322-6eab7e4c-cf67-11e7-85df-96ecca04b7c3.png)
![](https://user-images.githubusercontent.com/26904055/33138326-711537c2-cf67-11e7-99dd-f0914b3cf150.png)

Originally reported at https://github.com/usgs/magpy/issues/31 , but we weren't adding/changing these options and thought the upstream may have a preferred solution.

**Comment by leonro** [comment]
Issue solved in 906eef55fb0534e3f33169a406cc4d74ae18d67f. Ctrl-z is now used for initializing mysql databases.
