### ISSUE TITLE
Error when starting xmagpy on anaconda2, x64 with geomagpy 0.4.0

### ISSUE THREAD

**Issue by spark-corona** [geomagpy/magpy#90]
When starting xmagpy on anaconda2, x64 ubuntu 18.04 the following error occors.

~$ xmagpy
Traceback (most recent call last):
  File "/home/----/Software/Programming/anaconda2/bin/xmagpy", line 3, in <module>
    from magpy.gui.magpy_gui import MagPyApp
  File "/home/----/Software/Programming/anaconda2/lib/python2.7/site-packages/magpy/gui/magpy_gui.py", line 17, in <module>
    from wx.lib.pubsub import pub
  File "/home/----/Software/Programming/anaconda2/lib/python2.7/site-packages/wx/lib/pubsub/__init__.py", line 38, in <module>
    from pubsub import *
  File "/home/----/Software/Programming/anaconda2/lib/python2.7/site-packages/pubsub/pub.py", line 146
    def getDefaultPublisher() -> Publisher:
                              ^
SyntaxError: invalid syntax

Trying to replace wxpthon 4.0.3 with version 3.0.0 or 2.8 did NOT solve the problem.

Also trying to replace Pypubsub with version number 3.3.0 did NOT solve the problem.

--------------------------------

Maybe this could be an option for the needed change:

[https://stackoverflow.com/questions/5374451/importerror-cannot-import-name-publisher](https://stackoverflow.com/questions/5374451/importerror-cannot-import-name-publisher)

--------------------------------

**Comment by sparky-corona** [comment]
Think I found a workaround for the wxpython problem I always had when starting xmagpy on my laptop.

Looks like there are two packages which can be installed by

`conda install -c asmeurer pango`


By doing so conda forced a reinstall of wxpython 3.0.0.

Since then the problem disappeared.

best greet

Niko

**Comment by leonro** [comment]
An alternative would be:
conda install -c bjornfjohansson wxpython
which will install wxpython 3.0.2.0 (testet with MagPy 0.4.6)

**Comment by leonro** [comment]
Issue is fixed from 0.9.3 onwards when using python3
