### ISSUE TITLE
Add continuous integration to run tests automatically

### ISSUE THREAD

**Issue by jmfee-usgs** [geomagpy/magpy#94]
Travis CI is one option:
https://travis-ci.org/

This is an example travis configuration file:
https://github.com/usgs/geomag-algorithms/blob/master/.travis.yml

Could run the existing mptest utility with sample data files.

**Comment by mojca** [comment]
Travis has uncertain future, it might be better to use a different service if starting from scratch. Azure is one of the nice options.

**Comment by jmfee-usgs** [comment]
We use travis regularly, and I hadn't heard about any uncertainty.  I'm open to any system, and mainly interested in automated feedback on pull requests.

Looks like Azure could support parallel versions of python too.  Do you have any example scripts to use as a starting point?
https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops#use-multiple-python-versions

**Comment by leonro** [comment]
Since version 1.0.0 travis-ci is used for continuous integration.
