### ISSUE TITLE
Definitive data checking: yearmean* file not found

### ISSUE THREAD

**Issue by teraita** [geomagpy/magpy#96]
Environment: Version 0.4.7 (Python 2.7)  in Mac OS X 10.12

The definitive data checking routine can not find the yearmean.imo file from given path. The binaries are found.

<img width="2133" alt="MagPy_0 4 7_dd_check_read_yearmean_issue" src="https://user-images.githubusercontent.com/22149196/63014416-26b13e80-be97-11e9-915c-8a5f02454061.png">

**Comment by leonro** [comment]
The problem had its origin in a wrong interpretation of the comment section. If comments startet with 1 and 2 they were tried to be interpreted as data lines. This crashed and the file could not be read.
Solved that in 1aa8cf560232d7d6c3050332c0f0cc1a29bd5789

**Comment by leonro** [comment]
Issue is fixed from 0.9.3 onwards. Please note: yearmean files are freeform text files and it is very difficult to interprete all imaginable variations within a not well structured file.
